server:
  port: 8001
datasource:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: d2admin
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  database: 1
  pool:
    size: 1024
jwt:
  secret: 123456