server:
  port: 8001
datasource:
  host: 192.168.235.111
  port: 3308
  username: root
  password: 123456
  database: d2admin
redis:
  host: 192.168.235.111
  port: 6379
  password: 123456
  database: 1
  pool:
    size: 1024
jwt:
  secret: 123456
